import { Router } from 'express';
import { AccessControlError, requireActorPermission } from '../accessControl.js';
import { createCampaign, createSegment, deleteSegment, enqueueCampaignTest, listCampaigns, listRecipients, listSegments, previewCampaign, scheduleCampaign, setCampaignStatus, updateCampaignDraft, updateSegment } from './service.js';

export const campaignRouter = Router();
function error(res: any, cause: unknown): void { const code = cause instanceof AccessControlError ? cause.code : cause instanceof Error ? cause.message : 'CAMPAIGN_FAILED'; const status = code === 'FORBIDDEN' ? 403 : code === 'UNAUTHORIZED' ? 401 : code === 'CAMPAIGN_NOT_FOUND' ? 404 : 400; res.status(status).json({ code, message: code === 'FORBIDDEN' ? 'Você não tem permissão para gerenciar campanhas.' : 'Não foi possível concluir essa ação.' }); }
async function read(req: any): Promise<any> { return requireActorPermission(req, 'pessoas.visualizar'); }
async function communicate(req: any): Promise<any> { return requireActorPermission(req, 'clientes.comunicar'); }

campaignRouter.get('/api/customer-segments', async (req, res) => { try { const access = await read(req); res.json({ segments: await listSegments(access.empresaId) }); } catch (cause) { error(res, cause); } });
campaignRouter.post('/api/customer-segments', async (req, res) => { try { const access = await communicate(req); res.status(201).json(await createSegment(access.empresaId, access.actorUserId, { name: String(req.body?.name ?? ''), definition: req.body?.definition ?? {} })); } catch (cause) { error(res, cause); } });
campaignRouter.patch('/api/customer-segments/:id', async (req, res) => { try { const access = await communicate(req); res.json(await updateSegment(access.empresaId, req.params.id, req.body ?? {})); } catch (cause) { error(res, cause); } });
campaignRouter.delete('/api/customer-segments/:id', async (req, res) => { try { const access = await communicate(req); await deleteSegment(access.empresaId, req.params.id); res.status(204).end(); } catch (cause) { error(res, cause); } });
campaignRouter.get('/api/campaigns', async (req, res) => { try { const access = await read(req); res.json({ campaigns: await listCampaigns(access.empresaId) }); } catch (cause) { error(res, cause); } });
campaignRouter.post('/api/campaigns', async (req, res) => { try { const access = await communicate(req); res.status(201).json(await createCampaign(access.empresaId, access.actorUserId, req.body ?? {})); } catch (cause) { error(res, cause); } });
campaignRouter.patch('/api/campaigns/:id', async (req, res) => { try { const access = await communicate(req); res.json(await updateCampaignDraft(access.empresaId, req.params.id, req.body ?? {})); } catch (cause) { error(res, cause); } });
campaignRouter.post('/api/campaigns/:id/preview', async (req, res) => { try { const access = await read(req); res.json(await previewCampaign(access.empresaId, access.ownerUserId, req.body?.definition ?? {})); } catch (cause) { error(res, cause); } });
campaignRouter.post('/api/campaigns/:id/test', async (req, res) => { try { const access = await communicate(req); res.status(202).json(await enqueueCampaignTest(access.empresaId, access.actorUserId, req.params.id, typeof req.body?.phone === 'string' ? req.body.phone : undefined)); } catch (cause) { error(res, cause); } });
campaignRouter.post('/api/campaigns/:id/schedule', async (req, res) => { try { const access = await communicate(req); res.json(await scheduleCampaign(access.empresaId, access.ownerUserId, req.params.id, typeof req.body?.scheduledAt === 'string' ? req.body.scheduledAt : null)); } catch (cause) { error(res, cause); } });
for (const status of ['pause', 'resume', 'cancel'] as const) campaignRouter.post(`/api/campaigns/:id/${status}`, async (req, res) => { try { const access = await communicate(req); res.json(await setCampaignStatus(access.empresaId, req.params.id, status === 'pause' ? 'paused' : status === 'resume' ? 'running' : 'cancelled')); } catch (cause) { error(res, cause); } });
campaignRouter.get('/api/campaigns/:id/recipients', async (req, res) => { try { const access = await read(req); res.json({ recipients: await listRecipients(access.empresaId, req.params.id, Number(req.query.limit) || 50) }); } catch (cause) { error(res, cause); } });
