import { useEffect, useState } from 'react';
import { fetchCampaignRecipients, type Campaign, type CampaignRecipient } from '../../services/customerCampaignApi';

const statusLabel: Record<CampaignRecipient['status'], string> = { eligible: 'Elegível', suppressed: 'Suprimido', queued: 'Na fila', sending: 'Enviando', sent: 'Enviado', failed: 'Falhou', cancelled: 'Cancelado' };

export function CampaignRecipients({ token, campaign, onPause, onResume, onCancel }: { token: string | null; campaign: Campaign; onPause: () => void; onResume: () => void; onCancel: () => void }) {
  const [recipients, setRecipients] = useState<CampaignRecipient[]>([]);
  useEffect(() => { if (token) void fetchCampaignRecipients(token, campaign.id).then(setRecipients).catch(() => setRecipients([])); }, [campaign.id, token]);
  return <section className="space-y-4 p-4 md:p-6" aria-labelledby="campaign-recipients-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="campaign-recipients-title" className="text-[16px] font-semibold text-[var(--color-ink)]">Acompanhamento</h2><p className="text-[12px] text-[var(--color-ink-muted)]">{campaign.name} · {campaign.status === 'paused' ? 'Pausada' : campaign.status === 'running' ? 'Em andamento' : campaign.status === 'scheduled' ? 'Agendada' : campaign.status}</p></div><div className="flex flex-wrap gap-2">{campaign.status === 'paused' && <button type="button" onClick={onResume} className="min-h-[44px] rounded-lg bg-[var(--color-brand)] px-3 text-[13px] font-medium text-white">Retomar</button>}{(campaign.status === 'running' || campaign.status === 'scheduled') && <button type="button" onClick={onPause} className="min-h-[44px] rounded-lg border border-[var(--color-line)] px-3 text-[13px]">Pausar</button>}{!['completed', 'cancelled'].includes(campaign.status) && <button type="button" onClick={onCancel} className="min-h-[44px] rounded-lg border border-[var(--color-alert)] px-3 text-[13px] text-[var(--color-alert)]">Cancelar</button>}</div></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(['queued', 'sent', 'failed', 'suppressed'] as const).map((status) => <div key={status} className="rounded-xl bg-[var(--color-surface)] p-3"><strong className="block text-[18px] text-[var(--color-ink)]">{recipients.filter((item) => item.status === status).length}</strong><span className="text-[11px] text-[var(--color-ink-muted)]">{statusLabel[status]}</span></div>)}</div>
    <div className="overflow-hidden rounded-xl border border-[var(--color-line)] bg-[var(--color-surface)]"><ul>{recipients.map((recipient) => <li key={recipient.id} className="flex min-h-[52px] items-center justify-between gap-3 border-b border-[var(--color-line)] px-3 py-2 last:border-0"><span className="truncate text-[13px] text-[var(--color-ink)]">{recipient.name_snapshot || 'Cliente'}</span><span className="shrink-0 text-[11px] text-[var(--color-ink-muted)]">{recipient.suppression_reason ? ({ sem_telefone: 'Sem telefone', funcionario: 'Funcionário', conflito_identidade: 'Conflito de identidade', bloqueado: 'Bloqueado', opt_out: 'Opt-out' } as Record<string, string>)[recipient.suppression_reason] : statusLabel[recipient.status]}</span></li>)}</ul>{recipients.length === 0 && <p className="p-5 text-center text-[13px] text-[var(--color-ink-muted)]">Ainda não há destinatários para mostrar.</p>}</div>
  </section>;
}
