import { useEffect, useMemo, useState } from 'react';
import { canAdvanceCampaignStep, canScheduleCampaign, CAMPAIGN_STEPS, type CampaignStep } from '../../domain/campaignWizard';
import { createCampaign, previewCampaign, scheduleCampaign, sendCampaignTest, updateCampaign, type Campaign, type CampaignDefinition, type CampaignPreview } from '../../services/customerCampaignApi';
import { useDialogFocus } from '../../hooks/useDialogFocus';

const labels: Record<CampaignStep, string> = { audience: 'Público', message: 'Mensagem', test: 'Teste', review: 'Revisão', delivery: 'Enviar' };
const reasonLabels: Record<string, string> = { sem_telefone: 'Sem telefone', funcionario: 'Funcionário', conflito_identidade: 'Conflito de identidade', bloqueado: 'Bloqueado', opt_out: 'Não quer receber mensagens' };

export function CampaignWizard({ token, initialCampaign, onClose, onSaved }: { token: string | null; initialCampaign?: Campaign | null; onClose: () => void; onSaved: (campaign: Campaign) => void }) {
  const [step, setStep] = useState<CampaignStep>('audience');
  const [campaign, setCampaign] = useState<Campaign | null>(initialCampaign ?? null);
  const [name, setName] = useState(initialCampaign?.name ?? '');
  const [message, setMessage] = useState(initialCampaign?.message ?? '');
  const [phone, setPhone] = useState('');
  const [definition, setDefinition] = useState<CampaignDefinition>((initialCampaign?.segment_id ? {} : {}));
  const [preview, setPreview] = useState<CampaignPreview | null>(null);
  const [testSent, setTestSent] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [scheduledAt, setScheduledAt] = useState('');
  useDialogFocus(onClose);
  const progress = { hasAudience: true, hasMessage: message.trim().length > 0 && name.trim().length > 0, testSent, previewReady: Boolean(preview) };
  const suppressionCounts = useMemo(() => Object.entries((preview?.suppressed ?? []).reduce<Record<string, number>>((acc, item) => { acc[item.suppressionReason] = (acc[item.suppressionReason] ?? 0) + 1; return acc; }, {})), [preview]);

  useEffect(() => { if (!token || step !== 'audience') return; void previewCampaign(token, campaign?.id ?? 'preview', definition).then(setPreview).catch(() => setPreview(null)); }, [campaign?.id, definition, step, token]);
  const move = async (next: CampaignStep) => {
    if (!token || !canAdvanceCampaignStep(step, progress)) return;
    setError(null); setBusy(true);
    try {
      let saved = campaign;
      if (step === 'message' && !saved) saved = await createCampaign(token, { name: name.trim(), message: message.trim() });
      if (step === 'message' && saved) saved = await updateCampaign(token, saved.id, { name: name.trim(), message: message.trim() });
      if (saved) { setCampaign(saved); onSaved(saved); }
      if (next === 'review') setPreview(await previewCampaign(token, saved?.id ?? 'preview', definition));
      setStep(next);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível avançar.'); }
    finally { setBusy(false); }
  };
  const sendTest = async () => { if (!token || !campaign || !phone.trim() || !progress.hasMessage) return; setBusy(true); setError(null); try { await sendCampaignTest(token, campaign.id, phone.trim()); setTestSent(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível enviar o teste.'); } finally { setBusy(false); } };
  const deliver = async (at: string | null) => { if (!token || !campaign || !canScheduleCampaign(progress)) return; setBusy(true); setError(null); try { const result = await scheduleCampaign(token, campaign.id, at); onSaved(result.campaign); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível programar a campanha.'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 md:items-center md:p-4" role="dialog" aria-modal="true" aria-labelledby="campaign-wizard-title"><div className="flex max-h-[94vh] w-full max-w-2xl flex-col overflow-y-auto rounded-t-2xl bg-[var(--color-surface)] p-4 md:rounded-2xl md:p-6"><header className="mb-4 flex items-start justify-between gap-3"><div><h2 id="campaign-wizard-title" className="text-[17px] font-semibold text-[var(--color-ink)]">{initialCampaign ? 'Editar campanha' : 'Nova campanha'}</h2><p className="text-[12px] text-[var(--color-ink-muted)]">Monte o público, revise e escolha quando enviar.</p></div><button type="button" onClick={onClose} className="min-h-[44px] rounded-lg px-3 text-[13px]">Fechar</button></header>
    <nav aria-label="Etapas da campanha" className="mb-5 grid grid-cols-5 gap-1">{CAMPAIGN_STEPS.map((item, index) => <div key={item} className={`rounded-lg px-1 py-2 text-center text-[10px] ${item === step ? 'bg-[var(--color-brand-soft)] font-semibold text-[var(--color-brand-deep)]' : index < CAMPAIGN_STEPS.indexOf(step) ? 'text-[var(--color-brand-deep)]' : 'text-[var(--color-ink-faint)]'}`}><span className="block">{index + 1}</span>{labels[item]}</div>)}</nav>
    {error && <div role="alert" className="mb-3 rounded-lg bg-[var(--color-alert-soft)] p-3 text-[13px] text-[var(--color-alert)]">{error}</div>}
    {step === 'audience' && <div className="space-y-4"><div><h3 className="text-[15px] font-semibold text-[var(--color-ink)]">Quem deve receber?</h3><p className="text-[12px] text-[var(--color-ink-muted)]">A prévia já separa automaticamente quem não pode receber.</p></div><label className="block text-[12px] text-[var(--color-ink-muted)]">Atividade<select value={definition.activityState ?? ''} onChange={(e) => setDefinition({ ...definition, activityState: e.target.value ? e.target.value as CampaignDefinition['activityState'] : undefined })} className="mt-1 min-h-[44px] w-full rounded-lg border border-[var(--color-line)] bg-[var(--color-surface)] px-3 text-[14px]"><option value="">Todos os clientes</option><option value="active">Com pedidos</option><option value="inactive">Inativos</option><option value="never">Sem histórico</option></select></label><label className="block text-[12px] text-[var(--color-ink-muted)]">Pedidos entregues no mínimo<input type="number" min="0" value={definition.minOrders ?? ''} onChange={(e) => setDefinition({ ...definition, minOrders: e.target.value ? Number(e.target.value) : undefined })} className="mt-1 min-h-[44px] w-full rounded-lg border border-[var(--color-line)] px-3 text-[14px]" /></label><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-[var(--color-brand-soft)] p-3"><strong className="block text-[20px] text-[var(--color-brand-deep)]">{preview?.eligible.length ?? '—'}</strong><span className="text-[11px]">Elegíveis</span></div><div className="rounded-xl bg-[var(--color-surface-muted)] p-3"><strong className="block text-[20px] text-[var(--color-ink)]">{preview?.suppressed.length ?? '—'}</strong><span className="text-[11px]">Suprimidos</span></div></div>{suppressionCounts.length > 0 && <ul className="space-y-1 text-[12px] text-[var(--color-ink-muted)]">{suppressionCounts.map(([reason, count]) => <li key={reason} className="flex justify-between"><span>{reasonLabels[reason] ?? 'Não pode receber'}</span><strong>{count}</strong></li>)}</ul>}</div>}
    {step === 'message' && <div className="space-y-4"><label className="block text-[12px] text-[var(--color-ink-muted)]">Nome da campanha<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Ex.: Clientes inativos" className="mt-1 min-h-[44px] w-full rounded-lg border border-[var(--color-line)] px-3 text-[14px]" /></label><label className="block text-[12px] text-[var(--color-ink-muted)]">Mensagem<textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Escreva uma mensagem clara para seus clientes" rows={5} className="mt-1 w-full rounded-lg border border-[var(--color-line)] p-3 text-[14px]" /><span className="mt-1 block text-[11px]">Você pode usar <code>{'{{nome}}'}</code> para o primeiro nome.</span></label></div>}
    {step === 'test' && <div className="space-y-4"><h3 className="text-[15px] font-semibold text-[var(--color-ink)]">Faça um teste antes de revisar</h3><p className="text-[12px] text-[var(--color-ink-muted)]">Envie a mensagem para seu próprio número e confira como ela aparece.</p><label className="block text-[12px] text-[var(--color-ink-muted)]">Número para teste<input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="(XX) XXXXX-XXXX" className="mt-1 min-h-[44px] w-full rounded-lg border border-[var(--color-line)] px-3 text-[14px]" /></label><button type="button" onClick={() => void sendTest()} disabled={busy || !phone.trim()} className="min-h-[44px] rounded-lg bg-[var(--color-brand)] px-4 text-[13px] font-medium text-white disabled:opacity-50">{testSent ? 'Teste enviado' : 'Enviar teste'}</button>{testSent && <p className="text-[13px] text-[var(--color-brand-deep)]">Teste enviado. Você já pode seguir para a revisão.</p>}</div>}
    {step === 'review' && <div className="space-y-4"><h3 className="text-[15px] font-semibold text-[var(--color-ink)]">Revise antes de enviar</h3><div className="rounded-xl border border-[var(--color-line)] p-4"><p className="text-[12px] text-[var(--color-ink-muted)]">{name}</p><p className="mt-2 whitespace-pre-wrap text-[14px] text-[var(--color-ink)]">{message.replaceAll('{{nome}}', 'Nome')}</p></div><div className="grid grid-cols-2 gap-2"><p className="rounded-lg bg-[var(--color-brand-soft)] p-3 text-[13px]"><strong className="block text-[18px]">{preview?.eligible.length ?? 0}</strong>elegíveis</p><p className="rounded-lg bg-[var(--color-surface-muted)] p-3 text-[13px]"><strong className="block text-[18px]">{preview?.suppressed.length ?? 0}</strong>suprimidos</p></div><p className="text-[12px] text-[var(--color-ink-muted)]">A audiência será congelada no momento do envio.</p></div>}
    {step === 'delivery' && <div className="space-y-4"><h3 className="text-[15px] font-semibold text-[var(--color-ink)]">Quando enviar?</h3><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void deliver(null)} className="min-h-[44px] rounded-lg bg-[var(--color-brand)] px-4 text-[13px] font-medium text-white">Enviar agora</button><label className="flex min-h-[44px] items-center gap-2 rounded-lg border border-[var(--color-line)] px-3 text-[13px]">Agendar<input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} className="min-h-[40px] border-0 bg-transparent text-[13px]" /></label><button type="button" disabled={busy || !scheduledAt} onClick={() => void deliver(new Date(scheduledAt).toISOString())} className="min-h-[44px] rounded-lg border border-[var(--color-brand)] px-4 text-[13px] text-[var(--color-brand-deep)] disabled:opacity-50">Confirmar agendamento</button></div></div>}
    <footer className="mt-6 flex justify-between gap-2 border-t border-[var(--color-line)] pt-4"><button type="button" onClick={() => setStep(CAMPAIGN_STEPS[Math.max(0, CAMPAIGN_STEPS.indexOf(step) - 1)])} disabled={step === 'audience' || busy} className="min-h-[44px] rounded-lg px-3 text-[13px]">Voltar</button>{step !== 'delivery' && <button type="button" onClick={() => void move(CAMPAIGN_STEPS[CAMPAIGN_STEPS.indexOf(step) + 1])} disabled={busy || !canAdvanceCampaignStep(step, progress)} className="min-h-[44px] rounded-lg bg-[var(--color-brand)] px-4 text-[13px] font-medium text-white disabled:opacity-50">{busy ? 'Salvando…' : step === 'review' ? 'Escolher envio' : 'Continuar'}</button>}</footer>
  </div></div>;
}
