import { useCallback, useEffect, useMemo, useState } from 'react';
import { fetchCustomerMessages, retryCustomerMessage, sendCustomerMessage, type CustomerMessagesPage } from '../../services/customerApi';
import { aggregateCustomerMessages, canReadCustomerMessages, canSendCustomerMessage, isPrimaryWhatsAppJid, resolveLatestCustomerSessionId, type CustomerMessageItem, type CustomerMessagePermission } from '../../domain/customerMessages';
import type { ChatAttachment } from '../../types';
import { ConversationComposer } from '../chat/ConversationComposer';
import { ConversationThread, type ConversationThreadMessage } from '../chat/ConversationThread';

interface Props { token: string | null; personId: string; primaryJid: string | null; sessions?: Array<{ id: string; remoteJid: string }>; permissions: CustomerMessagePermission; onOpenAtendimento?: (sessionId: string) => void; }

export function CustomerMessagesTab({ token, personId, primaryJid, sessions = [], permissions, onOpenAtendimento }: Props) {
  const [page, setPage] = useState<CustomerMessagesPage>({ items: [], nextCursor: null, hasMore: false });
  const [sending, setSending] = useState(false);
  const [loading, setLoading] = useState(canReadCustomerMessages(permissions));
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const readAllowed = canReadCustomerMessages(permissions);
  const sendAllowed = canSendCustomerMessage(permissions) && isPrimaryWhatsAppJid(primaryJid);
  const load = useCallback(async (cursor: string | null = null) => { if (!token || !readAllowed) return; if (cursor) setLoadingMore(true); else setLoading(true); setError(null); try { const next = await fetchCustomerMessages(token, personId, cursor); setPage((previous) => cursor ? { ...next, items: [...previous.items, ...next.items] } : next); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar as mensagens.'); } finally { setLoading(false); setLoadingMore(false); } }, [personId, readAllowed, token]);
  useEffect(() => { void load(); }, [load]);
  const messages = useMemo<ConversationThreadMessage[]>(() => { const grouped = new Map<string, CustomerMessageItem['message'][] >(); for (const item of page.items) { const list = grouped.get(item.session_id) ?? []; list.push({ id: item.id, timestamp: item.sent_at, content: item.content, role: item.role === 'assistant' ? 'assistant' : 'user', status: item.outbound_status === 'failed' ? 'failed' : item.outbound_status === 'sending' ? 'sending' : 'sent', attachment: item.attachment }); grouped.set(item.session_id, list); } const apiItems = aggregateCustomerMessages(Array.from(grouped, ([id, messages]) => ({ id, messages }))); return apiItems.map(({ sessionId, message }) => ({ ...message, sessionId, role: message.role === 'assistant' ? 'assistant' as const : 'user' as const, content: message.content ?? null })).sort((a, b) => a.timestamp.localeCompare(b.timestamp)); }, [page.items]);
  const send = useCallback(async (text: string, attachment?: ChatAttachment) => { if (!token || !primaryJid || !sendAllowed) return; setSending(true); setError(null); try { await sendCustomerMessage(token, personId, primaryJid, { message: text, attachment }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível enviar a mensagem. Tente novamente.'); } finally { setSending(false); } }, [load, personId, primaryJid, sendAllowed, token]);
  const retry = useCallback(async (message: ConversationThreadMessage) => { if (!token || !sendAllowed) return; setError(null); try { await retryCustomerMessage(token, message.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível reenviar a mensagem. Tente novamente.'); } }, [load, sendAllowed, token]);
  if (!readAllowed) return <div className="flex flex-1 items-center justify-center p-6 text-[13px] text-[var(--color-ink-muted)]">Você não tem permissão para visualizar mensagens.</div>;
  const atendimentoSessionId = resolveLatestCustomerSessionId(sessions, messages);
  return <div className="flex min-h-0 flex-1 flex-col">{error && <div role="alert" className="flex items-center justify-between gap-2 border-b border-[var(--color-line)] px-4 py-2 text-[12px] text-[var(--color-alert)]"><span>{error}</span><button type="button" onClick={() => void load()} className="min-h-[44px] px-2 font-medium">Tentar novamente</button></div>}{loading ? <div role="status" className="flex flex-1 items-center justify-center text-[13px] text-[var(--color-ink-muted)]">Carregando mensagens…</div> : <><ConversationThread messages={messages} onRetry={retry} />{page.hasMore && <button type="button" disabled={loadingMore} onClick={() => void load(page.nextCursor)} className="mx-4 mb-2 min-h-[44px] rounded-lg border border-[var(--color-line)] text-[12px]">{loadingMore ? 'Carregando…' : 'Carregar mensagens anteriores'}</button>}<ConversationComposer canSend={sendAllowed} disabled={!primaryJid || sending} onSend={send} />{onOpenAtendimento && messages.length > 0 && atendimentoSessionId && <button type="button" onClick={() => onOpenAtendimento(atendimentoSessionId)} className="min-h-[44px] border-t border-[var(--color-line)] text-[12px] text-[var(--color-brand-deep)]">Abrir no Atendimento</button>}</>}</div>;
}
