import { useCallback, useEffect, useMemo, useState } from 'react';
import { fetchCustomerMessages, type CustomerMessagesPage } from '../../services/customerApi';
import { sendMessage } from '../../services/waApi';
import { aggregateCustomerMessages, canReadCustomerMessages, canSendCustomerMessage, isPrimaryWhatsAppJid, markOutboundFailed, markOutboundSent, createPendingOutboundMessage, type CustomerMessageItem, type CustomerMessagePermission } from '../../domain/customerMessages';
import type { ChatAttachment } from '../../types';
import { ConversationComposer } from '../chat/ConversationComposer';
import { ConversationThread, type ConversationThreadMessage } from '../chat/ConversationThread';

interface Props { token: string | null; personId: string; primaryJid: string | null; permissions: CustomerMessagePermission; onOpenAtendimento?: (sessionId: string) => void; }

export function CustomerMessagesTab({ token, personId, primaryJid, permissions, onOpenAtendimento }: Props) {
  const [page, setPage] = useState<CustomerMessagesPage>({ items: [], nextCursor: null, hasMore: false });
  const [outbound, setOutbound] = useState<ConversationThreadMessage[]>([]);
  const [loading, setLoading] = useState(canReadCustomerMessages(permissions));
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const readAllowed = canReadCustomerMessages(permissions);
  const sendAllowed = canSendCustomerMessage(permissions) && isPrimaryWhatsAppJid(primaryJid);
  const load = useCallback(async (cursor: string | null = null) => { if (!token || !readAllowed) return; if (cursor) setLoadingMore(true); else setLoading(true); setError(null); try { const next = await fetchCustomerMessages(token, personId, cursor); setPage((previous) => cursor ? { ...next, items: [...previous.items, ...next.items] } : next); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar as mensagens.'); } finally { setLoading(false); setLoadingMore(false); } }, [personId, readAllowed, token]);
  useEffect(() => { void load(); }, [load]);
  const messages = useMemo<ConversationThreadMessage[]>(() => { const grouped = new Map<string, CustomerMessageItem['message'][] >(); for (const item of page.items) { const list = grouped.get(item.session_id) ?? []; list.push({ id: item.id, timestamp: item.sent_at, content: item.content, role: item.role === 'assistant' ? 'assistant' : 'user', status: item.outbound_status === 'failed' ? 'failed' : item.outbound_status === 'sending' ? 'sending' : 'sent' }); grouped.set(item.session_id, list); } const apiItems = aggregateCustomerMessages(Array.from(grouped, ([id, messages]) => ({ id, messages }))); return [...apiItems.map(({ sessionId, message }) => ({ ...message, sessionId, role: message.role === 'assistant' ? 'assistant' as const : 'user' as const, content: message.content ?? null })), ...outbound].sort((a, b) => a.timestamp.localeCompare(b.timestamp)); }, [outbound, page.items]);
  const send = async (text: string, attachment?: ChatAttachment) => { if (!token || !primaryJid || !sendAllowed) return; const pending = createPendingOutboundMessage(`local-${Date.now()}`, page.items[0]?.session_id ?? 'pending', text, new Date().toISOString(), attachment); setOutbound((current) => [...current, { ...pending, sessionId: pending.id }]); try { await sendMessage(token, primaryJid, { message: text, attachment }); setOutbound((current) => current.map((item) => item.id === pending.id ? { ...markOutboundSent(item, `pending-${pending.id}`), sessionId: pending.id } : item)); } catch (cause) { setOutbound((current) => current.map((item) => item.id === pending.id ? { ...markOutboundFailed(item, cause instanceof Error ? cause.message : 'falha'), sessionId: pending.id } : item)); throw cause; } };
  const retry = async (message: ConversationThreadMessage) => { if (!token || !primaryJid || !sendAllowed) return; const pending = { ...message, status: 'sending' as const }; setOutbound((current) => current.map((item) => item.id === message.id ? pending : item)); try { await sendMessage(token, primaryJid, { message: message.content ?? '', attachment: message.attachment ?? undefined }); setOutbound((current) => current.map((item) => item.id === message.id ? { ...item, status: 'sent' as const } : item)); } catch { setOutbound((current) => current.map((item) => item.id === message.id ? { ...item, status: 'failed' as const } : item)); } };
  if (!readAllowed) return <div className="flex flex-1 items-center justify-center p-6 text-[13px] text-[var(--color-ink-muted)]">Você não tem permissão para visualizar mensagens.</div>;
  return <div className="flex min-h-0 flex-1 flex-col">{error && <div role="alert" className="flex items-center justify-between gap-2 border-b border-[var(--color-line)] px-4 py-2 text-[12px] text-[var(--color-alert)]"><span>{error}</span><button type="button" onClick={() => void load()} className="min-h-[44px] px-2 font-medium">Tentar novamente</button></div>}{loading ? <div role="status" className="flex flex-1 items-center justify-center text-[13px] text-[var(--color-ink-muted)]">Carregando mensagens…</div> : <><ConversationThread messages={messages} onRetry={retry} />{page.hasMore && <button type="button" disabled={loadingMore} onClick={() => void load(page.nextCursor)} className="mx-4 mb-2 min-h-[44px] rounded-lg border border-[var(--color-line)] text-[12px]">{loadingMore ? 'Carregando…' : 'Carregar mensagens anteriores'}</button>}<ConversationComposer canSend={sendAllowed} disabled={!primaryJid} onSend={send} />{onOpenAtendimento && messages[0] && <button type="button" onClick={() => onOpenAtendimento(messages[0].sessionId)} className="min-h-[44px] border-t border-[var(--color-line)] text-[12px] text-[var(--color-brand-deep)]">Abrir no Atendimento</button>}</>}</div>;
}
