import { Router } from 'express';
import { AccessControlError, requireActorPermission } from '../accessControl.js';
import { AUTOMATION_KINDS, getDefaultAutomationRule, validateAutomationRule, type AutomationKind } from './rules.js';
import { getServiceSupabase } from '../supabase.js';

export const automationRouter = Router();
function error(res: any, cause: unknown): void { const code = cause instanceof AccessControlError ? cause.code : cause instanceof Error ? cause.message : 'AUTOMATION_FAILED'; const status = code === 'FORBIDDEN' ? 403 : code === 'UNAUTHORIZED' ? 401 : 400; res.status(status).json({ code, message: code === 'FORBIDDEN' ? 'Você não tem permissão para gerenciar automações.' : 'Não foi possível concluir essa ação.' }); }
async function communicate(req: any): Promise<any> { return requireActorPermission(req, 'clientes.comunicar'); }
function kind(value: string): AutomationKind { if (!AUTOMATION_KINDS.includes(value as AutomationKind)) throw new Error('AUTOMATION_KIND_INVALID'); return value as AutomationKind; }
async function listRule(empresaId: string, k: AutomationKind): Promise<any> { const { data, error: dbError } = await getServiceSupabase().from('zelochat_automation_rules').select('*').eq('empresa_id', empresaId).eq('kind', k).maybeSingle(); if (dbError) throw dbError; return data ?? { ...getDefaultAutomationRule(k), empresa_id: empresaId }; }

automationRouter.get('/api/customer-automations', async (req, res) => { try { const access = await communicate(req); const { data, error: dbError } = await getServiceSupabase().from('zelochat_automation_rules').select('*').eq('empresa_id', access.empresaId).order('kind'); if (dbError) throw dbError; const byKind = new Map((data ?? []).map((row: any) => [row.kind, row])); res.json({ automations: AUTOMATION_KINDS.map((k) => byKind.get(k) ?? { ...getDefaultAutomationRule(k), empresa_id: access.empresaId }) }); } catch (cause) { error(res, cause); } });
automationRouter.patch('/api/customer-automations/:kind', async (req, res) => { try { const access = await communicate(req); const k = kind(req.params.kind); const input = req.body ?? {}; const checked = validateAutomationRule(k, input); if (!checked.ok) { res.status(400).json({ code: 'AUTOMATION_INVALID', message: 'Revise a mensagem, janela e limites da automação.', fields: checked.errors }); return; } const base = getDefaultAutomationRule(k); const values = { empresa_id: access.empresaId, id_usuario: access.ownerUserId, kind: k, enabled: Boolean(input.enabled ?? false), message: String(input.message ?? base.message).trim(), timezone: input.timezone ?? base.timezone, send_start: input.sendStart ?? base.sendStart, send_end: input.sendEnd ?? base.sendEnd, config: input.config ?? base.config, version: Number(input.version ?? base.version), updated_at: new Date().toISOString() }; const { data, error: dbError } = await getServiceSupabase().from('zelochat_automation_rules').upsert(values, { onConflict: 'empresa_id,kind' }).select('*').single(); if (dbError) throw dbError; res.json(data); } catch (cause) { error(res, cause); } });
for (const action of ['enable', 'disable'] as const) automationRouter.post(`/api/customer-automations/:kind/${action}`, async (req, res) => { try { const access = await communicate(req); const k = kind(req.params.kind); const current = await listRule(access.empresaId, k); const enabled = action === 'enable'; const checked = validateAutomationRule(k, { ...current, enabled }); if (!checked.ok) { res.status(400).json({ code: 'AUTOMATION_INVALID', message: 'Defina uma mensagem válida antes de habilitar.' }); return; } const { data, error: dbError } = await getServiceSupabase().from('zelochat_automation_rules').upsert({ empresa_id: access.empresaId, id_usuario: access.ownerUserId, kind: k, enabled, message: current.message ?? '', timezone: current.timezone ?? 'America/Sao_Paulo', send_start: current.send_start ?? '09:00', send_end: current.send_end ?? '20:00', config: current.config ?? {}, version: current.version ?? 1 }, { onConflict: 'empresa_id,kind' }).select('*').single(); if (dbError) throw dbError; res.json(data); } catch (cause) { error(res, cause); } });
automationRouter.post('/api/customer-automations/:kind/test', async (req, res) => { try { await communicate(req); const k = kind(req.params.kind); res.json({ ok: true, kind: k, status: 'preview', message: 'O teste ficará disponível no seu próprio número após a configuração.' }); } catch (cause) { error(res, cause); } });
automationRouter.get('/api/customer-automations/:kind/history', async (req, res) => { try { const access = await communicate(req); const k = kind(req.params.kind); const { data: rule, error: ruleError } = await getServiceSupabase().from('zelochat_automation_rules').select('id').eq('empresa_id', access.empresaId).eq('kind', k).maybeSingle(); if (ruleError) throw ruleError; if (!rule) { res.json({ dispatches: [] }); return; } const { data, error: dbError } = await getServiceSupabase().from('zelochat_automation_dispatches').select('*').eq('empresa_id', access.empresaId).eq('rule_id', rule.id).order('created_at', { ascending: false }).limit(Math.min(Number(req.query.limit) || 50, 100)); if (dbError) throw dbError; res.json({ dispatches: data ?? [] }); } catch (cause) { error(res, cause); } });
