import { Router, type Request, type Response } from 'express';
import { requireActorPermission } from '../accessControl.js';
import { parseCustomerFilters } from './filters.js';
import { getCustomerDetail, listCustomerMessages, listCustomerOrders, listCustomerTimeline, listCustomers } from './service.js';

export const customerRouter = Router();
async function actor(req: Request) { return requireActorPermission(req, 'pessoas.visualizar'); }
customerRouter.get('/api/customers', async (req: Request, res: Response) => { try { const access = await actor(req); const filters = parseCustomerFilters(req.query as Record<string, unknown>); const page = await listCustomers(access.empresaId, access.ownerUserId, filters); res.json(page); } catch (error) { res.status(400).json({ error: 'Não foi possível carregar os clientes.' }); } });
customerRouter.get('/api/customers/:personId', async (req: Request, res: Response) => { try { const access = await actor(req); const detail = await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId); if (!detail) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(detail); } catch { res.status(400).json({ error: 'Não foi possível carregar o cliente.' }); } });
customerRouter.get('/api/customers/:personId/messages', async (req: Request, res: Response) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerMessages(access.empresaId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });
customerRouter.get('/api/customers/:personId/orders', async (req: Request, res: Response) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerOrders(access.empresaId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });
customerRouter.get('/api/customers/:personId/timeline', async (req: Request, res: Response) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerTimeline(access.empresaId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });
