import { Router, type Request, type Response } from 'express';
import { requireActorPermission, type ActorAccessContext } from '../accessControl.js';
import { getServiceSupabase } from '../supabase.js';
import { parseCustomerFilters } from './filters.js';
import { getCustomerDetail, listCustomerMessages, listCustomerOrders, listCustomerTimeline, listCustomers } from './service.js';
import { createCustomersRouter, type CustomerMutationAccess, type CustomerWriteStore } from './mutations.js';

export const customerRouter = Router();
async function actor(req: Request): Promise<ActorAccessContext> { return requireActorPermission(req, 'pessoas.visualizar'); }

customerRouter.get('/api/customers', async (req, res) => { try { const access = await actor(req); res.json(await listCustomers(access.empresaId, access.ownerUserId, parseCustomerFilters(req.query as Record<string, unknown>))); } catch { res.status(400).json({ error: 'Não foi possível carregar os clientes.' }); } });
customerRouter.get('/api/customers/:personId', async (req, res) => { try { const access = await actor(req); const detail = await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId); if (!detail) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(detail); } catch { res.status(400).json({ error: 'Não foi possível carregar o cliente.' }); } });
customerRouter.get('/api/customers/:personId/messages', async (req, res) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerMessages(access.empresaId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });
customerRouter.get('/api/customers/:personId/orders', async (req, res) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerOrders(access.empresaId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });
customerRouter.get('/api/customers/:personId/timeline', async (req, res) => { try { const access = await actor(req); if (!await getCustomerDetail(access.empresaId, access.ownerUserId, req.params.personId)) { res.status(404).json({ error: 'Cliente não encontrado.' }); return; } res.json(await listCustomerTimeline(access.empresaId, access.ownerUserId, req.params.personId, typeof req.query.cursor === 'string' ? req.query.cursor : null, Number(req.query.limit) || 30)); } catch { res.status(403).json({ error: 'Você não tem permissão para visualizar clientes.' }); } });

function mutationAccess(context: ActorAccessContext): CustomerMutationAccess { return { isOwner: context.isOwner, permissions: context.permissions, empresaId: context.empresaId }; }

const mutationStore: CustomerWriteStore = {
  async getPersonEmpresaId(personId) { const db = getServiceSupabase(); const { data: person, error } = await db.from('pessoas').select('id_usuario').eq('id', personId).maybeSingle(); if (error || !person?.id_usuario) return null; const { data: empresa } = await db.from('empresa_perfil').select('id').eq('user_id', person.id_usuario).maybeSingle(); return empresa?.id ?? null; },
  async callRpc(name, args) { const { data, error } = await getServiceSupabase().rpc(name, args); return { data, error }; },
  async createCustomer(empresaId, patch) { const owner = await getServiceSupabase().from('empresa_perfil').select('user_id').eq('id', empresaId).maybeSingle(); if (!owner.data?.user_id) throw new Error('NOT_FOUND'); const phones = Array.isArray(patch.phones) ? patch.phones : []; const { data, error } = await getServiceSupabase().from('pessoas').insert({ id_usuario: owner.data.user_id, tipo: 'cliente', nome: typeof patch.name === 'string' ? patch.name.trim() : '', contato: typeof phones[0] === 'string' ? phones[0] : null }).select('*').single(); if (error) throw new Error(error.code ?? 'CUSTOMER_MUTATION_FAILED'); return data; },
  async updateCustomer(personId, empresaId, patch) { if (await this.getPersonEmpresaId(personId) !== empresaId) throw new Error('NOT_FOUND'); const values: Record<string, unknown> = {}; if (typeof patch.name === 'string') values.nome = patch.name.trim(); if (Array.isArray(patch.phones)) values.contato = typeof patch.phones[0] === 'string' ? patch.phones[0] : null; const { data, error } = await getServiceSupabase().from('pessoas').update(values).eq('id', personId).select('*').single(); if (error) throw new Error(error.code ?? 'CUSTOMER_MUTATION_FAILED'); return data; },
  async previewMerge(sourceId, targetId, empresaId) { if (await this.getPersonEmpresaId(sourceId) !== empresaId || await this.getPersonEmpresaId(targetId) !== empresaId) throw new Error('NOT_FOUND'); const db = getServiceSupabase(); const [source, target] = await Promise.all([db.from('pessoas').select('id,nome,contato').eq('id', sourceId), db.from('pessoas').select('id,nome,contato').eq('id', targetId)]); if (!source.data?.length || !target.data?.length) throw new Error('NOT_FOUND'); return { source: source.data[0], target: target.data[0], conversations: 0, orders: 0 }; },
  async executeMergeTransaction(sourceId, targetId, empresaId) { if (await this.getPersonEmpresaId(sourceId) !== empresaId || await this.getPersonEmpresaId(targetId) !== empresaId) throw new Error('NOT_FOUND'); const { error } = await getServiceSupabase().rpc('merge_zelochat_customers', { p_source_id: sourceId, p_target_id: targetId, p_empresa_id: empresaId }); if (error) throw new Error(error.code ?? 'CUSTOMER_MUTATION_FAILED'); },
};

const writeRouter = createCustomersRouter({ resolveAccess: (req) => requireActorPermission(req, 'pessoas.gerenciar').then(mutationAccess), store: mutationStore });
customerRouter.use('/api/customers', writeRouter);
